name: Generate SHA256 Checksum

on:
  push:
    branches: [main]

jobs:
  generate-sha256:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate SHA256 for script
        run: |
          sha256sum setup_harden_debian_ubuntu.sh > setup_harden_debian_ubuntu.sh.sha256

      - name: Commit & Push SHA256 File
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add setup_harden_debian_ubuntu.sh.sha256
          git commit -m "Auto-update SHA256 checksum"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
