name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
    paths: 
      - "du_setup.sh"
      - ".github/workflows/codacy.yml"
  pull_request:
    branches: [ "main" ]
    paths: 
      - "du_setup.sh"
  schedule:
    - cron: '44 7 * * 0'

permissions:
  contents: read

jobs:
  codacy-security-scan:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@d43360362776a6789b47b99ae8973510854e2d3d
        with:
          verbose: true
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Sanitize SARIF for GitHub
        run: |
          jq '(.runs |= unique_by(.tool.driver.name))' results.sarif > codacy_cleaned.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: codacy_cleaned.sarif
